spring:
  application:
    name: book_shop
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: 'true'
    hibernate:
      ddl-auto: update
  datasource:
    password: password
    url: jdbc:mysql://localhost:3306/book_shop
    username: root

