#spring.application.name=spring-data-jpa

spring:
  application:
    name: spring-data-jpa
  datasource:
    url: jdbc:mysql://localhost:3306/jdbc_test_db
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8085